default_model: "gpt4"
models:
  gpt4:
    type: "openai"
    endpoint: "https://api.openai.com/v1/chat/completions"
    api_key_env: "OPENAI_API_KEY"
  gpt3:
    type: "openai"
    endpoint: "https://api.openai.com/v1/completions"
    api_key_env: "OPENAI_API_KEY"
  claude-3-opus:
    type: "anthropic"
    endpoint: "https://api.anthropic.com/v1/messages"
    api_key_env: "ANTHROPIC_API_KEY"
  claude-3-sonnet:
    type: "anthropic"
    endpoint: "https://api.anthropic.com/v1/messages"
    api_key_env: "ANTHROPIC_API_KEY"
  gemini-pro:
    type: "google"
    endpoint: "https://generativelanguage.googleapis.com/v1beta/models/gemini-pro:generateContent"
    api_key_env: "GOOGLE_API_KEY"
  llama2:
    type: "llama"
    endpoint: "http://localhost:8000/generate"
  mistral-7b:
    type: "mistral"
    endpoint: "http://localhost:8001/generate"
  stablelm-zephyr:
    type: "stability"
    endpoint: "https://api.stability.ai/v1/generate"
    api_key_env: "STABILITY_API_KEY"
  huggingface-transformers:
    type: "huggingface"
    endpoint: "https://api-inference.huggingface.co/models"
    api_key_env: "HF_API_KEY"
  local-ollama:
    type: "ollama"
    endpoint: "http://localhost:11434/api/generate"
  openrouter-gpt4:
    type: "openrouter"
    endpoint: "https://openrouter.ai/api/v1/chat/completions"
    api_key_env: "OPENROUTER_API_KEY"
  openrouter-mixtral:
    type: "openrouter"
    endpoint: "https://openrouter.ai/api/v1/chat/completions"
    api_key_env: "OPENROUTER_API_KEY"
  openrouter-llama2:
    type: "openrouter"
    endpoint: "https://openrouter.ai/api/v1/chat/completions"
    api_key_env: "OPENROUTER_API_KEY"