[tool.poetry]
name = "makes-cli"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
rich = "12.6.0"
textual = "0.1.18"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
