permissions: read-all
concurrency:
  cancel-in-progress: true
  group: ${{ github.actor }}
jobs:
  linux_all:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@f095bcc56b7c2baf48f3ac70d6d6782f4f553222
      - uses: docker://docker.io/nixos/nix@sha256:c3db4c484f6b1ee6c9bb8ca90307cfbeca8ef88156840911356a677eeaff4845
        name: __all__
        with:
          args: sh -c "chown -R root:root /github/workspace && nix-env -if . && m . __all__"
  mac_all:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@f095bcc56b7c2baf48f3ac70d6d6782f4f553222
      - uses: cachix/install-nix-action@6ed004b9ccb68dbc28e7c85bee15fa93dbd214ac
      - name: __all__
        run: nix-env -if . && m . __all__

  linux_deployTerraform_module:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@f095bcc56b7c2baf48f3ac70d6d6782f4f553222
      - uses: docker://docker.io/nixos/nix@sha256:c3db4c484f6b1ee6c9bb8ca90307cfbeca8ef88156840911356a677eeaff4845
        name: /deployTerraform/module
        with:
          args: sh -c "chown -R root:root /github/workspace && nix-env -if . && m . /deployTerraform/module"
  macos_deployTerraform_module:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@f095bcc56b7c2baf48f3ac70d6d6782f4f553222
      - uses: cachix/install-nix-action@6ed004b9ccb68dbc28e7c85bee15fa93dbd214ac
      - name: /deployTerraform/module
        run: nix-env -if . && m . /deployTerraform/module

  linux_dev_makes:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@f095bcc56b7c2baf48f3ac70d6d6782f4f553222
      - uses: docker://docker.io/nixos/nix@sha256:c3db4c484f6b1ee6c9bb8ca90307cfbeca8ef88156840911356a677eeaff4845
        name: /dev/makes
        with:
          args: sh -c "chown -R root:root /github/workspace && nix-env -if . && m . /dev/makes"
        env:
          CACHIX_AUTH_TOKEN: ${{ secrets.CACHIX_AUTH_TOKEN }}
  macos_dev_makes:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@f095bcc56b7c2baf48f3ac70d6d6782f4f553222
      - uses: cachix/install-nix-action@6ed004b9ccb68dbc28e7c85bee15fa93dbd214ac
      - name: /dev/makes
        run: nix-env -if . && m . /dev/makes
        env:
          CACHIX_AUTH_TOKEN: ${{ secrets.CACHIX_AUTH_TOKEN }}

  linux_formatBash:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@f095bcc56b7c2baf48f3ac70d6d6782f4f553222
      - uses: docker://docker.io/nixos/nix@sha256:c3db4c484f6b1ee6c9bb8ca90307cfbeca8ef88156840911356a677eeaff4845
        name: /formatBash
        with:
          args: sh -c "chown -R root:root /github/workspace && nix-env -if . && m . /formatBash"
  macos_formatBash:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@f095bcc56b7c2baf48f3ac70d6d6782f4f553222
      - uses: cachix/install-nix-action@6ed004b9ccb68dbc28e7c85bee15fa93dbd214ac
      - name: /formatBash
        run: nix-env -if . && m . /formatBash

  linux_formatNix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@f095bcc56b7c2baf48f3ac70d6d6782f4f553222
      - uses: docker://docker.io/nixos/nix@sha256:c3db4c484f6b1ee6c9bb8ca90307cfbeca8ef88156840911356a677eeaff4845
        name: /formatNix
        with:
          args: sh -c "chown -R root:root /github/workspace && nix-env -if . && m . /formatNix"
  macos_formatNix:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@f095bcc56b7c2baf48f3ac70d6d6782f4f553222
      - uses: cachix/install-nix-action@6ed004b9ccb68dbc28e7c85bee15fa93dbd214ac
      - name: /formatNix
        run: nix-env -if . && m . /formatNix

  linux_formatTerraform:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@f095bcc56b7c2baf48f3ac70d6d6782f4f553222
      - uses: docker://docker.io/nixos/nix@sha256:c3db4c484f6b1ee6c9bb8ca90307cfbeca8ef88156840911356a677eeaff4845
        name: /formatTerraform
        with:
          args: sh -c "chown -R root:root /github/workspace && nix-env -if . && m . /formatTerraform"
  macos_formatTerraform:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@f095bcc56b7c2baf48f3ac70d6d6782f4f553222
      - uses: cachix/install-nix-action@6ed004b9ccb68dbc28e7c85bee15fa93dbd214ac
      - name: /formatTerraform
        run: nix-env -if . && m . /formatTerraform

  linux_formatYaml:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@f095bcc56b7c2baf48f3ac70d6d6782f4f553222
      - uses: docker://docker.io/nixos/nix@sha256:c3db4c484f6b1ee6c9bb8ca90307cfbeca8ef88156840911356a677eeaff4845
        name: /formatYaml
        with:
          args: sh -c "chown -R root:root /github/workspace && nix-env -if . && m . /formatYaml"
  macos_formatYaml:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@f095bcc56b7c2baf48f3ac70d6d6782f4f553222
      - uses: cachix/install-nix-action@6ed004b9ccb68dbc28e7c85bee15fa93dbd214ac
      - name: /formatYaml
        run: nix-env -if . && m . /formatYaml

  linux_lintBash:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@f095bcc56b7c2baf48f3ac70d6d6782f4f553222
      - uses: docker://docker.io/nixos/nix@sha256:c3db4c484f6b1ee6c9bb8ca90307cfbeca8ef88156840911356a677eeaff4845
        name: /lintBash
        with:
          args: sh -c "chown -R root:root /github/workspace && nix-env -if . && m . /lintBash"
  macos_lintBash:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@f095bcc56b7c2baf48f3ac70d6d6782f4f553222
      - uses: cachix/install-nix-action@6ed004b9ccb68dbc28e7c85bee15fa93dbd214ac
      - name: /lintBash
        run: nix-env -if . && m . /lintBash

  linux_tests_commitlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@f095bcc56b7c2baf48f3ac70d6d6782f4f553222
        with:
          fetch-depth: 0
      - uses: docker://docker.io/nixos/nix@sha256:c3db4c484f6b1ee6c9bb8ca90307cfbeca8ef88156840911356a677eeaff4845
        name: /tests/commitlint
        with:
          args: sh -c "chown -R root:root /github/workspace && nix-env -if . && m . /tests/commitlint"
  macos_tests_commitlint:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@f095bcc56b7c2baf48f3ac70d6d6782f4f553222
      - uses: cachix/install-nix-action@6ed004b9ccb68dbc28e7c85bee15fa93dbd214ac
      - name: /tests/commitlint
        run: nix-env -if . && m . /tests/commitlint

  linux_lintGitMailMap:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@f095bcc56b7c2baf48f3ac70d6d6782f4f553222
        with:
          fetch-depth: 0
      - uses: docker://docker.io/nixos/nix@sha256:c3db4c484f6b1ee6c9bb8ca90307cfbeca8ef88156840911356a677eeaff4845
        name: /lintGitMailMap
        with:
          args: sh -c "chown -R root:root /github/workspace && nix-env -if . && m . /lintGitMailMap"
  macos_lintGitMailMap:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@f095bcc56b7c2baf48f3ac70d6d6782f4f553222
      - uses: cachix/install-nix-action@6ed004b9ccb68dbc28e7c85bee15fa93dbd214ac
      - name: /lintGitMailMap
        run: nix-env -if . && m . /lintGitMailMap

  linux_lintNix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@f095bcc56b7c2baf48f3ac70d6d6782f4f553222
      - uses: docker://docker.io/nixos/nix@sha256:c3db4c484f6b1ee6c9bb8ca90307cfbeca8ef88156840911356a677eeaff4845
        name: /lintNix
        with:
          args: sh -c "chown -R root:root /github/workspace && nix-env -if . && m . /lintNix"
  macos_lintNix:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@f095bcc56b7c2baf48f3ac70d6d6782f4f553222
      - uses: cachix/install-nix-action@6ed004b9ccb68dbc28e7c85bee15fa93dbd214ac
      - name: /lintNix
        run: nix-env -if . && m . /lintNix

  linux_lintTerraform_module:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@f095bcc56b7c2baf48f3ac70d6d6782f4f553222
      - uses: docker://docker.io/nixos/nix@sha256:c3db4c484f6b1ee6c9bb8ca90307cfbeca8ef88156840911356a677eeaff4845
        name: /lintTerraform/module
        with:
          args: sh -c "chown -R root:root /github/workspace && nix-env -if . && m . /lintTerraform/module"
  macos_lintTerraform_module:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@f095bcc56b7c2baf48f3ac70d6d6782f4f553222
      - uses: cachix/install-nix-action@6ed004b9ccb68dbc28e7c85bee15fa93dbd214ac
      - name: /lintTerraform/module
        run: nix-env -if . && m . /lintTerraform/module

  linux_lintWithAjv_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@f095bcc56b7c2baf48f3ac70d6d6782f4f553222
      - uses: docker://docker.io/nixos/nix@sha256:c3db4c484f6b1ee6c9bb8ca90307cfbeca8ef88156840911356a677eeaff4845
        name: /lintWithAjv/test
        with:
          args: sh -c "chown -R root:root /github/workspace && nix-env -if . && m . /lintWithAjv/test"

  linux_testLicense:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@f095bcc56b7c2baf48f3ac70d6d6782f4f553222
      - uses: docker://docker.io/nixos/nix@sha256:c3db4c484f6b1ee6c9bb8ca90307cfbeca8ef88156840911356a677eeaff4845
        name: /testLicense
        with:
          args: sh -c "chown -R root:root /github/workspace && nix-env -if . && m . /testLicense"
  macos_testLicense:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@f095bcc56b7c2baf48f3ac70d6d6782f4f553222
      - uses: cachix/install-nix-action@6ed004b9ccb68dbc28e7c85bee15fa93dbd214ac
      - name: /testLicense
        run: nix-env -if . && m . /testLicense

  linux_tests_makeSearchPaths:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@f095bcc56b7c2baf48f3ac70d6d6782f4f553222
      - uses: docker://docker.io/nixos/nix@sha256:c3db4c484f6b1ee6c9bb8ca90307cfbeca8ef88156840911356a677eeaff4845
        name: /tests/makeSearchPaths
        with:
          args: sh -c "chown -R root:root /github/workspace && nix-env -if . && m . /tests/makeSearchPaths"
  macos_tests_makeSearchPaths:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@f095bcc56b7c2baf48f3ac70d6d6782f4f553222
      - uses: cachix/install-nix-action@6ed004b9ccb68dbc28e7c85bee15fa93dbd214ac
      - name: /tests/makeSearchPaths
        run: nix-env -if . && m . /tests/makeSearchPaths

  linux_tests_makeTemplate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@f095bcc56b7c2baf48f3ac70d6d6782f4f553222
      - uses: docker://docker.io/nixos/nix@sha256:c3db4c484f6b1ee6c9bb8ca90307cfbeca8ef88156840911356a677eeaff4845
        name: /tests/makeTemplate
        with:
          args: sh -c "chown -R root:root /github/workspace && nix-env -if . && m . /tests/makeTemplate"
  macos_tests_makeTemplate:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@f095bcc56b7c2baf48f3ac70d6d6782f4f553222
      - uses: cachix/install-nix-action@6ed004b9ccb68dbc28e7c85bee15fa93dbd214ac
      - name: /tests/makeTemplate
        run: nix-env -if . && m . /tests/makeTemplate

  linux_tests_makeScript:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@f095bcc56b7c2baf48f3ac70d6d6782f4f553222
      - uses: docker://docker.io/nixos/nix@sha256:c3db4c484f6b1ee6c9bb8ca90307cfbeca8ef88156840911356a677eeaff4845
        name: /tests/makeScript
        with:
          args: sh -c "chown -R root:root /github/workspace && nix-env -if . && m . /tests/makeScript"
  macos_tests_makeScript:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@f095bcc56b7c2baf48f3ac70d6d6782f4f553222
      - uses: cachix/install-nix-action@6ed004b9ccb68dbc28e7c85bee15fa93dbd214ac
      - name: /tests/makeScript
        run: nix-env -if . && m . /tests/makeScript

  linux_testTerraform_module:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@f095bcc56b7c2baf48f3ac70d6d6782f4f553222
      - uses: docker://docker.io/nixos/nix@sha256:c3db4c484f6b1ee6c9bb8ca90307cfbeca8ef88156840911356a677eeaff4845
        name: /testTerraform/module
        with:
          args: sh -c "chown -R root:root /github/workspace && nix-env -if . && m . /testTerraform/module"
  macos_testTerraform_module:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@f095bcc56b7c2baf48f3ac70d6d6782f4f553222
      - uses: cachix/install-nix-action@6ed004b9ccb68dbc28e7c85bee15fa93dbd214ac
      - name: /testTerraform/module
        run: nix-env -if . && m . /testTerraform/module

  linux_tests_computeOnAwsBatch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@f095bcc56b7c2baf48f3ac70d6d6782f4f553222
      - uses: docker://docker.io/nixos/nix@sha256:c3db4c484f6b1ee6c9bb8ca90307cfbeca8ef88156840911356a677eeaff4845
        name: /tests/computeOnAwsBatch
        with:
          args: sh -c "chown -R root:root /github/workspace && nix-env -if . && m . /tests/computeOnAwsBatch
  macos_tests_computeOnAwsBatch:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@f095bcc56b7c2baf48f3ac70d6d6782f4f553222
      - uses: cachix/install-nix-action@6ed004b9ccb68dbc28e7c85bee15fa93dbd214ac
      - name: /tests/computeOnAwsBatch
        run: nix-env -if . && m . /tests/computeOnAwsBatch
name: dev
on:
  pull_request:
    branches: [main]
