# cloudconfigs/k8s/services/frontend-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: discordlinked-frontend-service
  labels:
    app: discordlinked
    tier: frontend
spec:
  selector:
    app: discordlinked
    tier: frontend
  ports:
  - protocol: TCP
    port: 80 # Standard HTTP port for external access
    targetPort: 5173 # Frontend container port
  type: ClusterIP # Internal service, exposed externally via Ingress
