name: Release
on:
  push:
    tags:
      - v*
  workflow_dispatch:
    inputs:
      version:
        description: Version to release (e.g., v1.2.3)
        required: true
        type: string
permissions:
  contents: write
  packages: write
  pull-requests: read
jobs:
  validate-release:
    name: Validate Release
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.version }}
      is_prerelease: ${{ steps.version.outputs.is_prerelease }}
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          fetch-depth: 0
      - name: Determine version
        id: version
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            VERSION="${{ github.event.inputs.version }}"
          else
            VERSION="${GITHUB_REF#refs/tags/}"
          fi
          echo "version=$VERSION" >> "$GITHUB_OUTPUT"
          if [[ "$VERSION" =~ (alpha|beta|rc) ]]; then
            echo "is_prerelease=true" >> "$GITHUB_OUTPUT"
          else
            echo "is_prerelease=false" >> "$GITHUB_OUTPUT"
          fi
          echo "Release version: $VERSION"
          echo "Is prerelease: $([ "$VERSION" != "${VERSION/alpha/}" ] || [ "$VERSION" != "${VERSION/beta/}" ] || [ "$VERSION" != "${VERSION/rc/}" ] && echo "true" || echo "false")"
  wait-for-tests:
    name: Wait for Tests
    runs-on: ubuntu-latest
    steps:
      - name: Wait for test workflow
        uses: lewagon/wait-on-check-action@0dceb95e7c4cad8cc7422aee3885998f5cab9c79 # v1.4.0
        with:
          ref: ${{ github.sha }}
          check-name: Tests (Python 3.13)
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 30
          allowed-conclusions: success
  create-release:
    name: Create Release
    runs-on: ubuntu-latest
    needs:
      - validate-release
      - wait-for-tests
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          fetch-depth: 0
      - name: Generate changelog
        id: changelog
        run: |
          PREVIOUS_TAG=$(git describe --tags --abbrev=0 HEAD^ 2>/dev/null || echo "")
          if [ -z "$PREVIOUS_TAG" ]; then
            echo "changelog=Initial release" >> "$GITHUB_OUTPUT"
          else
            CHANGELOG=$(git log "${PREVIOUS_TAG}..HEAD" --pretty=format:"- %s (%h)" --no-merges)
            {
              echo "changelog<<EOF"
              echo "## Changes since $PREVIOUS_TAG"
              echo ""
              echo "$CHANGELOG"
              echo "EOF"
            } >> "$GITHUB_OUTPUT"
          fi
      - name: Create GitHub Release
        uses: softprops/action-gh-release@72f2c25fcb47643c292f7107632f7a47c1df5cd8 # v2
        with:
          tag_name: ${{ needs.validate-release.outputs.version }}
          name: Release ${{ needs.validate-release.outputs.version }}
          body: ${{ steps.changelog.outputs.changelog }}
          prerelease: ${{ needs.validate-release.outputs.is_prerelease == 'true' }}
          generate_release_notes: true
          make_latest: ${{ needs.validate-release.outputs.is_prerelease == 'false' }}
  notify-release:
    name: Notify Release
    runs-on: ubuntu-latest
    needs:
      - validate-release
      - create-release
    if: always() && needs.create-release.result == 'success'
    steps:
      - name: Release notification
        run: |-
          echo "🎉 Release ${{ needs.validate-release.outputs.version }} created successfully!"
          echo "📋 Check the release page for details"